// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HanumanInstitute.Satrimono.Models;

namespace HanumanInstitute.Satrimono.Migrations
{
    [DbContext(typeof(SatrimonoContext))]
    partial class SatrimonoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Satrimono.Models.Book", b =>
                {
                    b.Property<int>("Id");

                    b.Property<double?>("Accuracy");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<bool?>("IsFiction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT COLLATE NOCASE")
                        .HasDefaultValue("");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<string>("Url");

                    b.Property<int?>("Vibration");

                    b.HasKey("Id");

                    b.HasIndex("Author")
                        .HasName("Index_Author");

                    b.HasIndex("Id")
                        .HasName("Index_BookId");

                    b.HasIndex("Key")
                        .HasName("Index_BookKey");

                    b.ToTable("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
