//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanumanInstitute.CommonWebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HanumanInstitute.CommonWebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must call a valid api..
        /// </summary>
        internal static string BluePayInvalidApi {
            get {
                return ResourceManager.GetString("BluePayInvalidApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BluePayProcessor supports only USD and CAD currencies..
        /// </summary>
        internal static string BluePayInvalidCurrency {
            get {
                return ResourceManager.GetString("BluePayInvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration month is invalid: {0}..
        /// </summary>
        internal static string CreditCardExpirationMonthInvalid {
            get {
                return ResourceManager.GetString("CreditCardExpirationMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration year is invalid: {0}..
        /// </summary>
        internal static string CreditCardExpirationYearInvalid {
            get {
                return ResourceManager.GetString("CreditCardExpirationYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get latest exchange rate..
        /// </summary>
        internal static string CurrencyConverterFailed {
            get {
                return ResourceManager.GetString("CurrencyConverterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyConverter currently only supports converting from USD.
        /// </summary>
        internal static string CurrencyConverterSupportsOnlyUsd {
            get {
                return ResourceManager.GetString("CurrencyConverterSupportsOnlyUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodUnit was not recognized by PaymentPlanProcessor.GetPlanPeriod..
        /// </summary>
        internal static string GetPlanPeriodUnrecognizedUnit {
            get {
                return ResourceManager.GetString("GetPlanPeriodUnrecognizedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiritual Self Transformation: Order #{0} has been processed.
        /// </summary>
        internal static string InvoiceEmailTitle {
            get {
                return ResourceManager.GetString("InvoiceEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load resource &apos;{0}&apos;..
        /// </summary>
        internal static string InvoiceTemplateNotFound {
            get {
                return ResourceManager.GetString("InvoiceTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged out..
        /// </summary>
        internal static string LogoutManagerUserLoggedOut {
            get {
                return ResourceManager.GetString("LogoutManagerUserLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &quot;{0}&quot; doesn&apos;t exist in Ontraport..
        /// </summary>
        internal static string OntraportProductNotFound {
            get {
                return ResourceManager.GetString("OntraportProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned null Contact ID..
        /// </summary>
        internal static string OntraportReturnedNullContactId {
            get {
                return ResourceManager.GetString("OntraportReturnedNullContactId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method was not handled by PaymentProcessor..
        /// </summary>
        internal static string PaymentMethodNotHandled {
            get {
                return ResourceManager.GetString("PaymentMethodNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient account credits.
        /// </summary>
        internal static string PaymentProcessInsufficientCredits {
            get {
                return ResourceManager.GetString("PaymentProcessInsufficientCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPalForm only supports USD currency..
        /// </summary>
        internal static string PayPalFormInvalidCurrency {
            get {
                return ResourceManager.GetString("PayPalFormInvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityId must be set to pay via PayPal with quantity &gt; 1. Use your browser&apos;s inspect feature to get Ontraport quantity field ID..
        /// </summary>
        internal static string PayPalFormQuantityIdNull {
            get {
                return ResourceManager.GetString("PayPalFormQuantityIdNull", resourceCulture);
            }
        }
    }
}
