//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanumanInstitute.CommonWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HanumanInstitute.CommonWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file &apos;{1}&apos; exceeds {2} MB..
        /// </summary>
        internal static string FileExceedsMaxSize {
            get {
                return ResourceManager.GetString("FileExceedsMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file &apos;{1}&apos; is empty..
        /// </summary>
        internal static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; is not a valid JPG, GIF or PNG file..
        /// </summary>
        internal static string FileIsNotValidImage {
            get {
                return ResourceManager.GetString("FileIsNotValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority must be between 0 and 10, or null.
        /// </summary>
        internal static string SitemapPriorityOutOfRange {
            get {
                return ResourceManager.GetString("SitemapPriorityOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string ValueEmpty {
            get {
                return ResourceManager.GetString("ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be null or greater than 0..
        /// </summary>
        internal static string ValueMustBeNullOrPositive {
            get {
                return ResourceManager.GetString("ValueMustBeNullOrPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1}..
        /// </summary>
        internal static string ValueRange {
            get {
                return ResourceManager.GetString("ValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} and {2}..
        /// </summary>
        internal static string ValueRangeAnd {
            get {
                return ResourceManager.GetString("ValueRangeAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}..
        /// </summary>
        internal static string ValueRangeBetween {
            get {
                return ResourceManager.GetString("ValueRangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than {0}.
        /// </summary>
        internal static string ValueRangeGreaterThan {
            get {
                return ResourceManager.GetString("ValueRangeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than or equal to {0}.
        /// </summary>
        internal static string ValueRangeGreaterThanInclusive {
            get {
                return ResourceManager.GetString("ValueRangeGreaterThanInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than {0}.
        /// </summary>
        internal static string ValueRangeLessThan {
            get {
                return ResourceManager.GetString("ValueRangeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than or equal to {0}.
        /// </summary>
        internal static string ValueRangeLessThanInclusive {
            get {
                return ResourceManager.GetString("ValueRangeLessThanInclusive", resourceCulture);
            }
        }
    }
}
